name: Validate Version Sync

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run version sync check
        run: |
          chmod +x docs/repo-keeper/scripts/check-version-sync.sh
          ./docs/repo-keeper/scripts/check-version-sync.sh

      - name: Comment on PR (if failed)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## ❌ Version Sync Check Failed\n\nVersion numbers are inconsistent across the repository. Please run:\n\n```bash\n./docs/repo-keeper/scripts/check-version-sync.sh -v\n```\n\nAnd fix all version mismatches before merging.'
            })

      - name: Comment on PR (if passed)
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## ✅ Version Sync Check Passed\n\nAll version numbers are consistent!'
            })
